// Marketing and explainer copy for /billing/plans. Kept next to the component
// (like creditPacksCopy) because it is page-specific and covers every locale.
const copy = {
  en: {
    hero: {
      pill: 'Save up to {percent}% with yearly billing',
      titleLead: 'Talk. ',
      titleAccent: 'We’ll type.',
      titleLine2: 'For less than a coffee a month.',
      subtitle: 'The free plan is yours to keep. Upgrade when you need more cloud credits — cancel anytime, no hidden fees.',
      points: ['Open source · local models free forever', 'Secure payments by Stripe', 'Cancel anytime'],
      creditsPill: 'One-time purchase · no auto-renewal',
      creditsSubtitle: 'Monthly credits are used first, then add-on credits kick in automatically. Bigger packs cost less per credit.',
      creditsPoints: ['Added right after payment', 'No auto-renewal', 'Secure payments by Stripe'],
    },
    toolbar: {
      monthly: 'Monthly',
      yearly: 'Yearly',
      saveUpTo: 'Save up to {percent}%',
      remaining: '{credits} credits left this month',
      addon: '+{credits} add-on',
      unlimited: 'Unlimited credits this month',
      usage: '{percent}% of this month’s credits used',
      topUp: 'Top up',
    },
    card: {
      freeForever: 'Free forever',
      billedYearly: 'Billed {price} yearly',
      billedMonthly: 'Billed monthly · cancel anytime',
      save: 'Save {percent}%',
      dictation: '≈ {hours} h',
      dictationUnit: 'of cloud dictation / month',
      daily: '~{minutes} min a day · {credits} credits',
      unlimited: 'Unlimited',

    },
    estimator: {
      eyebrow: 'Find your plan in 30 seconds',
      title: 'How much do you talk each day?',
      lead: 'Drag the slider and we estimate your monthly credits with the real billing rules.',
      minutesLabel: 'Daily dictation',
      minutes: '{value} min',
      hours: '{value} h',
      aiLabel: 'AI rewrite & Ask Anything',
      ai: { none: 'Rarely', some: 'Sometimes', heavy: 'Often' },
      need: 'Estimated {credits} credits / month',
      fit: 'Uses about {used}% of its credits, leaving {left}% headroom for busy months.',
      fitUnlimited: 'Unlimited credits — no need to watch your usage.',
      over: 'About {credits} credits a month beyond {plan}. Pair it with an add-on pack.',
      overTitle: '{plan} + add-on',
      choose: 'Choose {plan}',
      note: 'Estimate assumes 1 credit per second of cloud audio; AI usage varies by model.',
    },
    how: {
      eyebrow: 'How credits work',
      title: 'One balance for every cloud feature',
      lead: 'No separate minutes and AI quotas — use what you need and only pay for what you use.',
      items: [
        { icon: '🎙', title: 'Cloud speech recognition', body: 'Billed by recorded audio length, so silence costs nothing.', tag: '1 second of audio = 1 credit' },
        { icon: '✦', title: 'AI rewrite & Ask Anything', body: 'Converted from model token usage. A typical polish uses only a few credits.', tag: 'Billed by tokens' },
        { icon: '⟳', title: 'Monthly first, then add-ons', body: 'Monthly credits reset every period. When they run out, add-on credits are used, earliest expiry first.', tag: 'Add-on credits last up to a year' },
      ],
    },
    compare: {
      eyebrow: 'Compare',
      title: 'Plans side by side',
      monthlyCredits: 'Monthly credits',
      dictation: 'Cloud dictation (approx.)',
      dictationValue: '{hours} h',
      ai: 'AI rewrite & Ask Anything',
      local: 'Local models (offline)',
      localValue: 'Unlimited',
      personas: 'Custom personas',
      addons: 'Add-on credit packs',
    },
    trust: [
      { title: 'Secure payments by Stripe', body: 'We never see or store your card.' },
      { title: 'Cancel anytime', body: 'Keep access until the period ends.' },
      { title: 'Open source', body: 'AGPL-3.0 — the code is public.' },
      { title: 'Privacy first', body: 'Your voice data belongs to you.' },
    ],
    faq: {
      title: 'Questions?',
      items: [
        { q: 'Can I keep using Typeflux for free?', a: 'Yes. Typeflux is open source and local models are free forever. The free plan also includes monthly credits for cloud AI processing.' },
        { q: 'What happens when I run out of credits?', a: 'You are never charged extra. Add-on credits are used automatically if you have any; otherwise switch to local models, buy an add-on pack, or upgrade.' },
        { q: 'Do monthly credits roll over?', a: 'No. Monthly credits reset each billing period. Add-on credits are the way to keep a reserve.' },
        { q: 'How do I cancel?', a: 'Manage your subscription from Typeflux. After canceling you keep your plan until the current period ends.' },
      ],
    },
    final: {
      title: 'Let your voice do the typing',
      subtitle: 'Yearly {plan} costs just {price} a day.',
      fallback: 'Start free and upgrade whenever you need more.',
      cta: 'Upgrade to {plan}',
    },
  },
  'zh-CN': {
    hero: {
      pill: '按年付最高省 {percent}%',
      titleLead: '你说内容，',
      titleAccent: '我来打字',
      titleLine2: '每月不到一杯咖啡的钱。',
      subtitle: '免费版永久可用。需要更多云端额度时再升级，随时取消，没有任何隐藏费用。',
      points: ['开源 · 本地模型永久免费', 'Stripe 安全支付', '随时取消订阅'],
      creditsPill: '一次购买 · 不自动续费',
      creditsSubtitle: '月度积分用完后自动启用加购额度，买得越多单价越低。',
      creditsPoints: ['付款后即时到账', '不自动续费', 'Stripe 安全支付'],
    },
    toolbar: {
      monthly: '按月付',
      yearly: '按年付',
      saveUpTo: '最高省 {percent}%',
      remaining: '本月剩 {credits} 积分',
      addon: '加购 +{credits}',
      unlimited: '本月积分不限量',
      usage: '本月积分已用 {percent}%',
      topUp: '加购额度',
    },
    card: {
      freeForever: '永久免费',
      billedYearly: '按年付 {price}',
      billedMonthly: '按月付，随时取消',
      save: '省 {percent}%',
      dictation: '≈ {hours} 小时',
      dictationUnit: '云端语音输入 / 月',
      daily: '每天约 {minutes} 分钟 · {credits} 积分',
      unlimited: '不限量',

    },
    estimator: {
      eyebrow: '30 秒找到合适的套餐',
      title: '你每天会说多少话？',
      lead: '拖动滑块，我们按真实计费规则帮你估算每月积分。',
      minutesLabel: '每天语音输入时长',
      minutes: '{value} 分钟',
      hours: '{value} 小时',
      aiLabel: 'AI 改写 / 随便问 使用频率',
      ai: { none: '几乎不用', some: '偶尔', heavy: '经常' },
      need: '预计每月消耗 {credits} 积分',
      fit: '用量约为额度的 {used}%，还有 {left}% 余量应对忙碌月份。',
      fitUnlimited: '积分不限量，无需关心用量。',
      over: '每月超出{plan}约 {credits} 积分，建议搭配加购额度包。',
      overTitle: '{plan} + 加购',
      choose: '选择{plan}',
      note: '按云端音频每秒 1 积分估算；AI 用量因模型而异。',
    },
    how: {
      eyebrow: '积分怎么算',
      title: '一套积分，所有云端能力通用',
      lead: '不用分别购买识别时长和 AI 次数 —— 用多少扣多少，透明可查。',
      items: [
        { icon: '🎙', title: '云端语音识别', body: '按实际录音时长计费，不说话不扣费。', tag: '1 秒音频 = 1 积分' },
        { icon: '✦', title: 'AI 改写与「随便问」', body: '按模型 token 用量折算，一次润色通常只需少量积分。', tag: '按 token 计费' },
        { icon: '⟳', title: '先用月度，再用加购', body: '月度积分每个周期重置；用完后自动使用加购额度，按到期时间先后扣减。', tag: '加购额度最长一年有效' },
      ],
    },
    compare: {
      eyebrow: '套餐对比',
      title: '一眼看清差别',
      monthlyCredits: '每月积分',
      dictation: '云端语音输入（约）',
      dictationValue: '{hours} 小时',
      ai: 'AI 改写 / 随便问',
      local: '本地模型（离线）',
      localValue: '不限量',
      personas: '自定义人设',
      addons: '加购额度包',
    },
    trust: [
      { title: 'Stripe 安全支付', body: '我们不接触、不保存你的卡号' },
      { title: '随时取消', body: '取消后可用到当期结束' },
      { title: '完全开源', body: 'AGPL-3.0，代码公开可审计' },
      { title: '隐私为先', body: '声音数据只属于你' },
    ],
    faq: {
      title: '还有疑问？',
      items: [
        { q: '不付费可以一直用吗？', a: '可以。Typeflux 是开源软件，本地模型永久免费；免费版每月还附赠积分，用于云端 AI 处理。' },
        { q: '积分用完了会怎样？', a: '不会额外扣费。有加购额度时会自动使用；否则可以切换到本地模型，或购买加购额度、升级套餐。' },
        { q: '月度积分会累积到下个月吗？', a: '不会。月度积分每个计费周期重置；想长期储备额度，可以购买加购额度。' },
        { q: '如何取消订阅？', a: '在 Typeflux 中管理订阅即可取消，取消后当前计费周期结束前仍可正常使用。' },
      ],
    },
    final: {
      title: '今天就把打字交给声音',
      subtitle: '年付{plan}，每天只要 {price}。',
      fallback: '先免费用起来，需要更多时再升级。',
      cta: '升级到{plan}',
    },
  },
  'zh-TW': {
    hero: {
      pill: '按年付最高省 {percent}%',
      titleLead: '你說內容，',
      titleAccent: '我來打字',
      titleLine2: '每月不到一杯咖啡的錢。',
      subtitle: '免費版永久可用。需要更多雲端額度時再升級，隨時取消，沒有任何隱藏費用。',
      points: ['開源 · 本機模型永久免費', 'Stripe 安全付款', '隨時取消訂閱'],
      creditsPill: '一次購買 · 不自動續費',
      creditsSubtitle: '每月點數用完後自動啟用加購點數，買得越多單價越低。',
      creditsPoints: ['付款後立即入帳', '不自動續費', 'Stripe 安全付款'],
    },
    toolbar: {
      monthly: '按月付',
      yearly: '按年付',
      saveUpTo: '最高省 {percent}%',
      remaining: '本月剩 {credits} 點數',
      addon: '加購 +{credits}',
      unlimited: '本月點數不限量',
      usage: '本月點數已用 {percent}%',
      topUp: '加購點數',
    },
    card: {
      freeForever: '永久免費',
      billedYearly: '按年付 {price}',
      billedMonthly: '按月付，隨時取消',
      save: '省 {percent}%',
      dictation: '≈ {hours} 小時',
      dictationUnit: '雲端語音輸入 / 月',
      daily: '每天約 {minutes} 分鐘 · {credits} 點數',
      unlimited: '不限量',

    },
    estimator: {
      eyebrow: '30 秒找到合適的方案',
      title: '你每天會說多少話？',
      lead: '拖動滑桿，我們依實際計費規則幫你估算每月點數。',
      minutesLabel: '每天語音輸入時長',
      minutes: '{value} 分鐘',
      hours: '{value} 小時',
      aiLabel: 'AI 改寫 / 隨便問 使用頻率',
      ai: { none: '幾乎不用', some: '偶爾', heavy: '經常' },
      need: '預計每月消耗 {credits} 點數',
      fit: '用量約為額度的 {used}%，還有 {left}% 餘裕應付忙碌月份。',
      fitUnlimited: '點數不限量，無需在意用量。',
      over: '每月超出{plan}約 {credits} 點數，建議搭配加購點數包。',
      overTitle: '{plan} + 加購',
      choose: '選擇{plan}',
      note: '依雲端音訊每秒 1 點數估算；AI 用量因模型而異。',
    },
    how: {
      eyebrow: '點數怎麼算',
      title: '一套點數，所有雲端功能通用',
      lead: '不用分別購買辨識時長和 AI 次數 —— 用多少扣多少，透明可查。',
      items: [
        { icon: '🎙', title: '雲端語音辨識', body: '依實際錄音時長計費，不說話不扣點。', tag: '1 秒音訊 = 1 點數' },
        { icon: '✦', title: 'AI 改寫與「隨便問」', body: '依模型 token 用量換算，一次潤飾通常只需少量點數。', tag: '依 token 計費' },
        { icon: '⟳', title: '先用每月點數，再用加購', body: '每月點數每個週期重置；用完後自動使用加購點數，依到期時間先後扣除。', tag: '加購點數最長一年有效' },
      ],
    },
    compare: {
      eyebrow: '方案比較',
      title: '一眼看清差別',
      monthlyCredits: '每月點數',
      dictation: '雲端語音輸入（約）',
      dictationValue: '{hours} 小時',
      ai: 'AI 改寫 / 隨便問',
      local: '本機模型（離線）',
      localValue: '不限量',
      personas: '自訂人設',
      addons: '加購點數包',
    },
    trust: [
      { title: 'Stripe 安全付款', body: '我們不接觸、不儲存你的卡號' },
      { title: '隨時取消', body: '取消後可用到當期結束' },
      { title: '完全開源', body: 'AGPL-3.0，程式碼公開可稽核' },
      { title: '隱私優先', body: '聲音資料只屬於你' },
    ],
    faq: {
      title: '還有疑問？',
      items: [
        { q: '不付費可以一直使用嗎？', a: '可以。Typeflux 是開源軟體，本機模型永久免費；免費版每月還附贈點數，用於雲端 AI 處理。' },
        { q: '點數用完了會怎樣？', a: '不會額外收費。有加購點數時會自動使用；否則可以切換到本機模型，或購買加購點數、升級方案。' },
        { q: '每月點數會累積到下個月嗎？', a: '不會。每月點數每個計費週期重置；想長期儲備，可以購買加購點數。' },
        { q: '如何取消訂閱？', a: '在 Typeflux 中管理訂閱即可取消，取消後在當前計費週期結束前仍可正常使用。' },
      ],
    },
    final: {
      title: '今天就把打字交給聲音',
      subtitle: '年付{plan}，每天只要 {price}。',
      fallback: '先免費用起來，需要更多時再升級。',
      cta: '升級到{plan}',
    },
  },
  ja: {
    hero: {
      pill: '年払いで最大 {percent}% お得',
      titleLead: '話すだけで、',
      titleAccent: '文字になる。',
      titleLine2: '月額はコーヒー 1 杯以下。',
      subtitle: '無料プランはずっと使えます。クラウドのクレジットが足りなくなったらアップグレード。いつでも解約でき、隠れた費用はありません。',
      points: ['オープンソース · ローカルモデルは永久無料', 'Stripe による安全な決済', 'いつでも解約可能'],
      creditsPill: '1 回限りの購入 · 自動更新なし',
      creditsSubtitle: '月間クレジットを使い切ると追加クレジットが自動で使われます。大きいパックほど単価が下がります。',
      creditsPoints: ['支払い後すぐに反映', '自動更新なし', 'Stripe による安全な決済'],
    },
    toolbar: {
      monthly: '月払い',
      yearly: '年払い',
      saveUpTo: '最大 {percent}% お得',
      remaining: '今月の残り {credits} クレジット',
      addon: '追加 +{credits}',
      unlimited: '今月のクレジットは無制限',
      usage: '今月のクレジットを {percent}% 使用済み',
      topUp: 'クレジットを追加',
    },
    card: {
      freeForever: 'ずっと無料',
      billedYearly: '年額 {price}',
      billedMonthly: '月払い · いつでも解約可能',
      save: '{percent}% お得',
      dictation: '約 {hours} 時間',
      dictationUnit: 'のクラウド音声入力 / 月',
      daily: '1 日約 {minutes} 分 · {credits} クレジット',
      unlimited: '無制限',

    },
    estimator: {
      eyebrow: '30 秒でぴったりのプランを',
      title: '1 日にどれくらい話しますか？',
      lead: 'スライダーを動かすと、実際の課金ルールで月間クレジットを試算します。',
      minutesLabel: '1 日の音声入力時間',
      minutes: '{value} 分',
      hours: '{value} 時間',
      aiLabel: 'AI リライト / 何でも聞く の頻度',
      ai: { none: 'ほぼ使わない', some: 'ときどき', heavy: 'よく使う' },
      need: '月間の推定消費 {credits} クレジット',
      fit: 'クレジットの約 {used}% を使用し、忙しい月にも {left}% の余裕があります。',
      fitUnlimited: 'クレジット無制限なので使用量を気にする必要はありません。',
      over: '{plan}を毎月約 {credits} クレジット超えます。追加パックとの併用がおすすめです。',
      overTitle: '{plan} + 追加',
      choose: '{plan}を選ぶ',
      note: 'クラウド音声 1 秒 = 1 クレジットで試算。AI の使用量はモデルによって異なります。',
    },
    how: {
      eyebrow: 'クレジットの仕組み',
      title: 'すべてのクラウド機能に使える 1 つの残高',
      lead: '認識時間と AI 回数を別々に買う必要はありません。使った分だけ、明快に。',
      items: [
        { icon: '🎙', title: 'クラウド音声認識', body: '実際の録音時間で課金。話していない時間は消費しません。', tag: '音声 1 秒 = 1 クレジット' },
        { icon: '✦', title: 'AI リライトと「何でも聞く」', body: 'モデルのトークン使用量から換算。1 回の推敲はわずかなクレジットで済みます。', tag: 'トークン課金' },
        { icon: '⟳', title: '月間クレジットから先に使用', body: '月間クレジットは期間ごとにリセット。使い切ると追加クレジットを有効期限の早い順に使用します。', tag: '追加クレジットは最長 1 年有効' },
      ],
    },
    compare: {
      eyebrow: 'プラン比較',
      title: '違いがひと目でわかる',
      monthlyCredits: '月間クレジット',
      dictation: 'クラウド音声入力（目安）',
      dictationValue: '{hours} 時間',
      ai: 'AI リライト / 何でも聞く',
      local: 'ローカルモデル（オフライン）',
      localValue: '無制限',
      personas: 'カスタムペルソナ',
      addons: '追加クレジットパック',
    },
    trust: [
      { title: 'Stripe による安全な決済', body: 'カード情報を受け取ることも保存することもありません' },
      { title: 'いつでも解約', body: '解約後も期間終了まで利用できます' },
      { title: 'オープンソース', body: 'AGPL-3.0、コードは公開されています' },
      { title: 'プライバシー重視', body: '音声データはあなたのものです' },
    ],
    faq: {
      title: 'よくある質問',
      items: [
        { q: 'ずっと無料で使えますか？', a: 'はい。Typeflux はオープンソースで、ローカルモデルは永久無料です。無料プランにはクラウド AI 処理用の月間クレジットも含まれます。' },
        { q: 'クレジットを使い切るとどうなりますか？', a: '追加料金は発生しません。追加クレジットがあれば自動で使われ、なければローカルモデルへの切り替え、追加パックの購入、アップグレードを選べます。' },
        { q: '月間クレジットは繰り越せますか？', a: 'いいえ。月間クレジットは請求期間ごとにリセットされます。残高を蓄えたい場合は追加クレジットをご利用ください。' },
        { q: '解約方法は？', a: 'Typeflux のサブスクリプション管理から解約できます。解約後も現在の請求期間が終わるまで利用できます。' },
      ],
    },
    final: {
      title: 'タイピングは声に任せよう',
      subtitle: '{plan}の年払いなら 1 日わずか {price}。',
      fallback: 'まずは無料で。必要になったらいつでもアップグレード。',
      cta: '{plan}にアップグレード',
    },
  },
  ko: {
    hero: {
      pill: '연간 결제 시 최대 {percent}% 할인',
      titleLead: '말하면, ',
      titleAccent: '입력은 저희가.',
      titleLine2: '한 달 커피 한 잔 값도 안 됩니다.',
      subtitle: '무료 요금제는 계속 사용할 수 있습니다. 클라우드 크레딧이 더 필요할 때 업그레이드하세요. 언제든 해지할 수 있고 숨은 비용은 없습니다.',
      points: ['오픈 소스 · 로컬 모델 영구 무료', 'Stripe 안전 결제', '언제든 해지 가능'],
      creditsPill: '1회 구매 · 자동 갱신 없음',
      creditsSubtitle: '월간 크레딧을 다 쓰면 추가 크레딧이 자동으로 사용됩니다. 큰 팩일수록 단가가 낮습니다.',
      creditsPoints: ['결제 후 바로 지급', '자동 갱신 없음', 'Stripe 안전 결제'],
    },
    toolbar: {
      monthly: '월간 결제',
      yearly: '연간 결제',
      saveUpTo: '최대 {percent}% 할인',
      remaining: '이번 달 {credits} 크레딧 남음',
      addon: '추가 +{credits}',
      unlimited: '이번 달 크레딧 무제한',
      usage: '이번 달 크레딧 {percent}% 사용',
      topUp: '크레딧 추가',
    },
    card: {
      freeForever: '영구 무료',
      billedYearly: '연 {price} 결제',
      billedMonthly: '월간 결제 · 언제든 해지',
      save: '{percent}% 할인',
      dictation: '약 {hours}시간',
      dictationUnit: '클라우드 음성 입력 / 월',
      daily: '하루 약 {minutes}분 · {credits} 크레딧',
      unlimited: '무제한',

    },
    estimator: {
      eyebrow: '30초 만에 맞는 요금제 찾기',
      title: '하루에 얼마나 말하시나요?',
      lead: '슬라이더를 움직이면 실제 과금 규칙으로 월간 크레딧을 추정합니다.',
      minutesLabel: '하루 음성 입력 시간',
      minutes: '{value}분',
      hours: '{value}시간',
      aiLabel: 'AI 다듬기 / 무엇이든 물어보기 사용 빈도',
      ai: { none: '거의 안 함', some: '가끔', heavy: '자주' },
      need: '월 예상 사용량 {credits} 크레딧',
      fit: '크레딧의 약 {used}%를 사용하며, 바쁜 달을 위해 {left}% 여유가 있습니다.',
      fitUnlimited: '크레딧 무제한이라 사용량을 신경 쓸 필요가 없습니다.',
      over: '매달 {plan}보다 약 {credits} 크레딧이 더 필요합니다. 추가 크레딧 팩과 함께 사용하세요.',
      overTitle: '{plan} + 추가',
      choose: '{plan} 선택',
      note: '클라우드 오디오 1초당 1 크레딧 기준 추정이며, AI 사용량은 모델에 따라 다릅니다.',
    },
    how: {
      eyebrow: '크레딧 계산 방식',
      title: '모든 클라우드 기능에 쓰는 하나의 잔액',
      lead: '인식 시간과 AI 횟수를 따로 살 필요 없이, 쓴 만큼만 투명하게 차감됩니다.',
      items: [
        { icon: '🎙', title: '클라우드 음성 인식', body: '실제 녹음 시간 기준으로 과금되며, 말하지 않으면 차감되지 않습니다.', tag: '오디오 1초 = 1 크레딧' },
        { icon: '✦', title: 'AI 다듬기와 무엇이든 물어보기', body: '모델 토큰 사용량으로 환산하며, 한 번 다듬는 데 적은 크레딧만 듭니다.', tag: '토큰 기준 과금' },
        { icon: '⟳', title: '월간 크레딧 먼저, 그다음 추가 크레딧', body: '월간 크레딧은 매 기간 초기화됩니다. 다 쓰면 만료가 빠른 추가 크레딧부터 사용합니다.', tag: '추가 크레딧 최대 1년 유효' },
      ],
    },
    compare: {
      eyebrow: '요금제 비교',
      title: '차이를 한눈에',
      monthlyCredits: '월간 크레딧',
      dictation: '클라우드 음성 입력(약)',
      dictationValue: '{hours}시간',
      ai: 'AI 다듬기 / 무엇이든 물어보기',
      local: '로컬 모델(오프라인)',
      localValue: '무제한',
      personas: '맞춤 페르소나',
      addons: '추가 크레딧 팩',
    },
    trust: [
      { title: 'Stripe 안전 결제', body: '카드 정보를 보거나 저장하지 않습니다' },
      { title: '언제든 해지', body: '해지 후에도 기간 종료까지 사용 가능' },
      { title: '오픈 소스', body: 'AGPL-3.0, 코드 공개' },
      { title: '개인정보 우선', body: '음성 데이터는 사용자의 것입니다' },
    ],
    faq: {
      title: '궁금한 점이 있으신가요?',
      items: [
        { q: '무료로 계속 사용할 수 있나요?', a: '네. Typeflux는 오픈 소스이며 로컬 모델은 영구 무료입니다. 무료 요금제에는 클라우드 AI 처리용 월간 크레딧도 포함됩니다.' },
        { q: '크레딧을 다 쓰면 어떻게 되나요?', a: '추가 요금은 없습니다. 추가 크레딧이 있으면 자동으로 사용되고, 없으면 로컬 모델로 전환하거나 추가 팩 구매 또는 업그레이드를 할 수 있습니다.' },
        { q: '월간 크레딧이 이월되나요?', a: '아니요. 월간 크레딧은 결제 기간마다 초기화됩니다. 여유분을 모아 두려면 추가 크레딧을 이용하세요.' },
        { q: '어떻게 해지하나요?', a: 'Typeflux의 구독 관리에서 해지할 수 있으며, 해지 후에도 현재 결제 기간이 끝날 때까지 사용할 수 있습니다.' },
      ],
    },
    final: {
      title: '이제 타이핑은 목소리에 맡기세요',
      subtitle: '{plan} 연간 결제는 하루 {price}입니다.',
      fallback: '무료로 시작하고 필요할 때 업그레이드하세요.',
      cta: '{plan}로 업그레이드',
    },
  },
}

export function billingPlansCopy(lang) {
  return copy[lang] || copy.en
}
