// Copy for the credit pack tab of /billing/plans. Kept next to the component
// (like BillingResultPage) because the backend only localizes en and zh-CN.
const copy = {
  en: {
    tabs: { label: 'Billing options', plans: 'Subscription plans', credits: 'Add-on credits' },
    title: 'Top up your credits.',
    loadingTitle: 'Loading credit packs',
    loadingSummary: 'We are securely retrieving the credit packs and your current balance.',
    errorTitle: 'Credit packs are temporarily unavailable',
    errorSummary: 'We could not load the credit packs. Check your connection and try again.',
    emptyTitle: 'No credit packs are available',
    emptySummary: 'There are no purchasable credit packs right now. Please check back later.',
    retry: 'Try again',
    billingUnavailable: 'Billing is temporarily unavailable. You can still review credit packs, but checkout is disabled.',
    balance: {
      label: 'Your credit balance',
      monthly: 'Monthly remaining',
      addon: 'Add-on remaining',
      nextExpiry: 'Next expiry',
      unlimited: 'Unlimited',
      noExpiry: 'Nothing expiring',
      expiryDetail: '{credits} on {date}',
      usageOrder: 'Monthly credits are used first. Add-on credits are used automatically after they run out, earliest expiry first.',
      total: 'Available credits',
      orderTitle: 'Usage order',
      steps: ['Monthly credits first', 'Then add-on credits, automatically', 'Earliest expiring add-ons first'],
    },
    pack: {
      recommended: 'Recommended',
      credits: '{credits} credits',
      bonus: '+{percent}% bonus',
      validity: 'Valid for {days} days',
      unavailable: 'Unavailable',
      select: 'Select {name}',
      perTenK: '{price} per 10k credits',
      bestValue: 'Best value',
    },
    purchase: {
      policy: 'One-time purchase. Non-refundable after purchase. Valid for {days} days.',
      agree: 'I understand that this one-time purchase is non-refundable and expires {days} days after purchase.',
      buy: 'Buy {credits} credits · {price}',
      choosePack: 'Choose a credit pack',
      opening: 'Opening Stripe…',
    },
    summary: { title: 'Order summary', pack: 'Pack', credits: 'Credits', validity: 'Valid for', validityValue: '{days} days', after: 'Balance after purchase', total: 'Total' },
    secure: 'Payments are securely processed by Stripe',
    upsell: { title: 'Need more every month?', body: 'A subscription gives you a bigger monthly allowance at a lower price per credit.', action: 'View subscription plans →' },
    errors: {
      failed: 'Stripe Checkout could not be opened. Please try again.',
      rateLimited: 'You have reached the limit of 10 credit pack orders in 24 hours. Please try again later.',
      reconciliation: 'Billing setup for your account needs a quick check by our support team. Please contact support before trying again.',
      requestExpired: 'That checkout attempt has expired. Please start a new purchase.',
      billingDisabled: 'Billing is temporarily disabled. Please try again later.',
    },
    canceled: 'Checkout was canceled and no payment was made. Your selection has been kept.',
    result: {
      pendingTitle: 'Confirming your payment',
      pendingSummary: 'Stripe is confirming the payment. Credits are added as soon as it succeeds.',
      grantedTitle: 'Credits added',
      grantedSummary: '{credits} credits have been added to your account.',
      grantedSummaryUnknown: 'Your add-on credits have been added to your account.',
      failedTitle: 'Payment was not completed',
      failedSummary: 'The payment failed, so no credits were added. You can choose a pack and try again.',
      delayedTitle: 'Payment is still processing',
      delayedSummary: 'Some payment methods take longer to confirm. Credits are added automatically once the payment succeeds — check your purchase history later.',
      unverifiedTitle: 'Payment submitted',
      unverifiedSummary: 'We cannot check the order from this page because the billing link has expired. Open Typeflux to see your latest balance.',
      returnToApp: 'Return to Typeflux',
      checkAgain: 'Check again',
    },
    history: {
      title: 'Purchase history',
      show: 'Show purchase history',
      hide: 'Hide purchase history',
      loading: 'Loading purchase history…',
      empty: 'No credit pack purchases yet.',
      error: 'Purchase history could not be loaded.',
      loadMore: 'Load more',
      date: 'Purchased',
      pack: 'Pack',
      credits: 'Credits',
      remaining: 'Remaining',
      expires: 'Expires',
      status: 'Status',
      manual: 'Compensation',
      statuses: { active: 'Active', frozen: 'Frozen', revoked: 'Revoked', expired: 'Expired' },
    },
    packs: {},
  },
  'zh-CN': {
    tabs: { label: '购买方式', plans: '订阅套餐', credits: '加购额度' },
    title: '加购额度，随用随充。',
    loadingTitle: '正在加载加购额度',
    loadingSummary: '正在安全获取可购买的额度包和你当前的余额。',
    errorTitle: '加购额度暂时不可用',
    errorSummary: '无法加载额度包，请检查网络后重试。',
    emptyTitle: '暂无可购买的额度包',
    emptySummary: '当前没有可购买的额度包，请稍后再来看看。',
    retry: '重试',
    billingUnavailable: '支付暂时不可用。你仍可以浏览额度包，但暂时无法下单。',
    balance: {
      label: '当前额度余额',
      monthly: '月度剩余',
      addon: '加购剩余',
      nextExpiry: '最近一次到期',
      unlimited: '不限量',
      noExpiry: '暂无即将到期',
      expiryDetail: '{date} 到期 {credits}',
      usageOrder: '先使用月度额度；月度额度用完后，自动使用加购额度，按到期时间先后扣减。',
      total: '当前可用积分',
      orderTitle: '扣减顺序',
      steps: ['优先使用本月月度积分', '用完后自动使用加购额度', '多笔加购按到期时间先后扣减'],
    },
    pack: {
      recommended: '推荐',
      credits: '{credits} credits',
      bonus: '多送 {percent}%',
      validity: '有效期 {days} 天',
      unavailable: '暂不可购买',
      select: '选择{name}',
      perTenK: '每万积分 {price}',
      bestValue: '单价最低',
    },
    purchase: {
      policy: '一次性购买，购买后不支持退款，有效期 {days} 天。',
      agree: '我已了解：本次为一次性购买，购买后不支持退款，额度自购买起 {days} 天后到期。',
      buy: '购买 {credits} credits · {price}',
      choosePack: '请选择额度包',
      opening: '正在打开 Stripe…',
    },
    summary: { title: '订单摘要', pack: '额度包', credits: '积分', validity: '有效期', validityValue: '{days} 天', after: '购买后可用', total: '应付' },
    secure: '由 Stripe 安全处理付款',
    upsell: { title: '每个月都不够用？', body: '订阅套餐的每月额度更多，每积分单价也更低。', action: '查看订阅套餐 →' },
    errors: {
      failed: '无法打开 Stripe Checkout，请重试。',
      rateLimited: '24 小时内最多购买 10 笔额度包，请稍后再试。',
      reconciliation: '你的账户账单设置需要客服核对，请联系客服后再重试。',
      requestExpired: '这次下单已过期，请重新发起购买。',
      billingDisabled: '支付暂时关闭，请稍后再试。',
    },
    canceled: '已取消支付，本次没有扣款。你之前的选择已保留。',
    result: {
      pendingTitle: '正在确认支付',
      pendingSummary: 'Stripe 正在确认这笔支付，成功后额度会立即到账。',
      grantedTitle: '额度已到账',
      grantedSummary: '已到账 {credits} credits。',
      grantedSummaryUnknown: '加购额度已到账。',
      failedTitle: '支付未完成',
      failedSummary: '支付失败，额度没有到账。你可以重新选择额度包再试一次。',
      delayedTitle: '支付仍在处理中',
      delayedSummary: '部分支付方式需要更长时间确认。支付成功后额度会自动到账，稍后可在购买记录中查看。',
      unverifiedTitle: '支付已提交',
      unverifiedSummary: '账单链接已过期，无法在此页面查询订单状态。请打开 Typeflux 查看最新余额。',
      returnToApp: '返回 Typeflux',
      checkAgain: '再次查询',
    },
    history: {
      title: '购买记录',
      show: '展开购买记录',
      hide: '收起购买记录',
      loading: '正在加载购买记录…',
      empty: '还没有购买过额度包。',
      error: '购买记录加载失败。',
      loadMore: '加载更多',
      date: '购买时间',
      pack: '额度包',
      credits: '数量',
      remaining: '剩余',
      expires: '到期时间',
      status: '状态',
      manual: '补偿',
      statuses: { active: '可用', frozen: '已冻结', revoked: '已收回', expired: '已过期' },
    },
    packs: {},
  },
  'zh-TW': {
    tabs: { label: '購買方式', plans: '訂閱方案', credits: '加購額度' },
    title: '加購額度，隨用隨充。',
    loadingTitle: '正在載入加購額度',
    loadingSummary: '正在安全取得可購買的額度包和你目前的餘額。',
    errorTitle: '加購額度暫時無法使用',
    errorSummary: '無法載入額度包，請檢查網路後重試。',
    emptyTitle: '暫無可購買的額度包',
    emptySummary: '目前沒有可購買的額度包，請稍後再來看看。',
    retry: '重試',
    billingUnavailable: '付款暫時無法使用。你仍可瀏覽額度包，但暫時無法下單。',
    balance: {
      label: '目前額度餘額',
      monthly: '每月剩餘',
      addon: '加購剩餘',
      nextExpiry: '最近一次到期',
      unlimited: '不限量',
      noExpiry: '暫無即將到期',
      expiryDetail: '{date} 到期 {credits}',
      usageOrder: '先使用每月額度；每月額度用完後，自動使用加購額度，依到期時間先後扣減。',
      total: '目前可用點數',
      orderTitle: '扣除順序',
      steps: ['優先使用本月點數', '用完後自動使用加購點數', '多筆加購依到期時間先後扣除'],
    },
    pack: {
      recommended: '推薦',
      credits: '{credits} credits',
      bonus: '多送 {percent}%',
      validity: '有效期 {days} 天',
      unavailable: '暫不可購買',
      select: '選擇{name}',
      perTenK: '每萬點數 {price}',
      bestValue: '單價最低',
    },
    purchase: {
      policy: '一次性購買，購買後不支援退款，有效期 {days} 天。',
      agree: '我已了解：本次為一次性購買，購買後不支援退款，額度自購買起 {days} 天後到期。',
      buy: '購買 {credits} credits · {price}',
      choosePack: '請選擇額度包',
      opening: '正在開啟 Stripe…',
    },
    summary: { title: '訂單摘要', pack: '點數包', credits: '點數', validity: '有效期', validityValue: '{days} 天', after: '購買後可用', total: '應付' },
    secure: '由 Stripe 安全處理付款',
    upsell: { title: '每個月都不夠用？', body: '訂閱方案的每月額度更多，每點單價也更低。', action: '查看訂閱方案 →' },
    errors: {
      failed: '無法開啟 Stripe Checkout，請重試。',
      rateLimited: '24 小時內最多購買 10 筆額度包，請稍後再試。',
      reconciliation: '你的帳戶帳單設定需要客服核對，請聯絡客服後再重試。',
      requestExpired: '這次下單已過期，請重新發起購買。',
      billingDisabled: '付款暫時關閉，請稍後再試。',
    },
    canceled: '已取消付款，本次沒有扣款。你先前的選擇已保留。',
    result: {
      pendingTitle: '正在確認付款',
      pendingSummary: 'Stripe 正在確認這筆付款，成功後額度會立即入帳。',
      grantedTitle: '額度已入帳',
      grantedSummary: '已入帳 {credits} credits。',
      grantedSummaryUnknown: '加購額度已入帳。',
      failedTitle: '付款未完成',
      failedSummary: '付款失敗，額度沒有入帳。你可以重新選擇額度包再試一次。',
      delayedTitle: '付款仍在處理中',
      delayedSummary: '部分付款方式需要較長時間確認。付款成功後額度會自動入帳，稍後可在購買紀錄中查看。',
      unverifiedTitle: '付款已送出',
      unverifiedSummary: '帳單連結已過期，無法在此頁面查詢訂單狀態。請開啟 Typeflux 查看最新餘額。',
      returnToApp: '返回 Typeflux',
      checkAgain: '再次查詢',
    },
    history: {
      title: '購買紀錄',
      show: '展開購買紀錄',
      hide: '收合購買紀錄',
      loading: '正在載入購買紀錄…',
      empty: '還沒有購買過額度包。',
      error: '購買紀錄載入失敗。',
      loadMore: '載入更多',
      date: '購買時間',
      pack: '額度包',
      credits: '數量',
      remaining: '剩餘',
      expires: '到期時間',
      status: '狀態',
      manual: '補償',
      statuses: { active: '可用', frozen: '已凍結', revoked: '已收回', expired: '已過期' },
    },
    packs: {
      pack_s: { name: '小額包', description: '滿足偶爾的額外用量' },
      pack_m: { name: '中額包', description: '比基礎檔多送 10% 額度' },
      pack_l: { name: '大額包', description: '比基礎檔多送 15% 額度' },
      pack_xl: { name: '超大包', description: '比基礎檔多送 25% 額度' },
    },
  },
  ja: {
    tabs: { label: '購入方法', plans: 'サブスクリプション', credits: '追加クレジット' },
    title: 'クレジットを追加購入。',
    loadingTitle: 'クレジットパックを読み込み中',
    loadingSummary: '購入可能なクレジットパックと現在の残高を安全に取得しています。',
    errorTitle: 'クレジットパックを一時的に利用できません',
    errorSummary: 'クレジットパックを読み込めませんでした。接続を確認して再度お試しください。',
    emptyTitle: '購入可能なクレジットパックはありません',
    emptySummary: '現在購入可能なクレジットパックはありません。後ほどご確認ください。',
    retry: '再試行',
    billingUnavailable: '決済は一時的に利用できません。パックの確認はできますが、購入はできません。',
    balance: {
      label: 'クレジット残高',
      monthly: '月間残り',
      addon: '追加分の残り',
      nextExpiry: '次の有効期限',
      unlimited: '無制限',
      noExpiry: '期限切れ予定なし',
      expiryDetail: '{date} に {credits}',
      usageOrder: '月間クレジットが先に使用され、使い切ると追加クレジットが有効期限の早い順に自動で使われます。',
      total: '利用可能なクレジット',
      orderTitle: '消費の順番',
      steps: ['まず今月の月間クレジット', '使い切ると追加クレジットを自動で使用', '有効期限の早い追加クレジットから'],
    },
    pack: {
      recommended: 'おすすめ',
      credits: '{credits} クレジット',
      bonus: '+{percent}% ボーナス',
      validity: '有効期間 {days} 日',
      unavailable: '購入不可',
      select: '{name} を選択',
      perTenK: '1 万クレジットあたり {price}',
      bestValue: '最安単価',
    },
    purchase: {
      policy: '一回限りの購入です。購入後の返金はできません。有効期間は {days} 日です。',
      agree: 'この一回限りの購入は返金できず、購入から {days} 日後に失効することを理解しました。',
      buy: '{credits} クレジットを購入 · {price}',
      choosePack: 'パックを選択してください',
      opening: 'Stripe を開いています…',
    },
    summary: { title: 'ご注文内容', pack: 'パック', credits: 'クレジット', validity: '有効期間', validityValue: '{days} 日', after: '購入後の残高', total: 'お支払い' },
    secure: 'お支払いは Stripe で安全に処理されます',
    upsell: { title: '毎月足りませんか？', body: 'サブスクリプションなら月間クレジットが多く、1 クレジットあたりの単価も下がります。', action: 'サブスクリプションを見る →' },
    errors: {
      failed: 'Stripe Checkout を開けませんでした。再度お試しください。',
      rateLimited: '24 時間あたりの購入上限（10 件）に達しました。しばらくしてから再度お試しください。',
      reconciliation: 'アカウントの請求設定にサポートによる確認が必要です。サポートにお問い合わせのうえ、再度お試しください。',
      requestExpired: 'この購入手続きは期限切れです。新しく購入を開始してください。',
      billingDisabled: '決済は一時的に停止しています。後ほど再度お試しください。',
    },
    canceled: 'チェックアウトはキャンセルされ、支払いは発生していません。選択内容は保持されています。',
    result: {
      pendingTitle: 'お支払いを確認中',
      pendingSummary: 'Stripe がお支払いを確認しています。完了次第クレジットが追加されます。',
      grantedTitle: 'クレジットを追加しました',
      grantedSummary: '{credits} クレジットがアカウントに追加されました。',
      grantedSummaryUnknown: '追加クレジットがアカウントに追加されました。',
      failedTitle: 'お支払いが完了しませんでした',
      failedSummary: 'お支払いに失敗したため、クレジットは追加されていません。パックを選んで再度お試しください。',
      delayedTitle: 'お支払いを処理中です',
      delayedSummary: '支払い方法によっては確認に時間がかかります。完了後に自動でクレジットが追加されます。後ほど購入履歴をご確認ください。',
      unverifiedTitle: 'お支払いを送信しました',
      unverifiedSummary: '請求リンクの有効期限が切れたため、このページでは注文を確認できません。Typeflux を開いて最新の残高をご確認ください。',
      returnToApp: 'Typeflux へ戻る',
      checkAgain: '再確認',
    },
    history: {
      title: '購入履歴',
      show: '購入履歴を表示',
      hide: '購入履歴を閉じる',
      loading: '購入履歴を読み込み中…',
      empty: 'クレジットパックの購入履歴はまだありません。',
      error: '購入履歴を読み込めませんでした。',
      loadMore: 'さらに読み込む',
      date: '購入日',
      pack: 'パック',
      credits: 'クレジット',
      remaining: '残り',
      expires: '有効期限',
      status: '状態',
      manual: '補填',
      statuses: { active: '有効', frozen: '凍結中', revoked: '取消済み', expired: '期限切れ' },
    },
    packs: {
      pack_s: { name: 'スモール', description: 'たまに必要な追加分に' },
      pack_m: { name: 'ミディアム', description: '基本レートより 10% 多いクレジット' },
      pack_l: { name: 'ラージ', description: '基本レートより 15% 多いクレジット' },
      pack_xl: { name: 'エクストララージ', description: '基本レートより 25% 多いクレジット' },
    },
  },
  ko: {
    tabs: { label: '구매 방식', plans: '구독 요금제', credits: '추가 크레딧' },
    title: '필요한 만큼 크레딧을 충전하세요.',
    loadingTitle: '크레딧 팩을 불러오는 중',
    loadingSummary: '구매 가능한 크레딧 팩과 현재 잔액을 안전하게 가져오고 있습니다.',
    errorTitle: '크레딧 팩을 일시적으로 사용할 수 없습니다',
    errorSummary: '크레딧 팩을 불러오지 못했습니다. 연결을 확인하고 다시 시도해 주세요.',
    emptyTitle: '구매 가능한 크레딧 팩이 없습니다',
    emptySummary: '현재 구매 가능한 크레딧 팩이 없습니다. 나중에 다시 확인해 주세요.',
    retry: '다시 시도',
    billingUnavailable: '결제를 일시적으로 사용할 수 없습니다. 팩은 확인할 수 있지만 구매는 비활성화되어 있습니다.',
    balance: {
      label: '크레딧 잔액',
      monthly: '월간 잔여',
      addon: '추가 크레딧 잔여',
      nextExpiry: '다음 만료',
      unlimited: '무제한',
      noExpiry: '만료 예정 없음',
      expiryDetail: '{date}에 {credits}',
      usageOrder: '월간 크레딧이 먼저 사용되며, 소진되면 추가 크레딧이 만료일이 빠른 순서로 자동 사용됩니다.',
      total: '사용 가능한 크레딧',
      orderTitle: '차감 순서',
      steps: ['이번 달 월간 크레딧 먼저', '소진되면 추가 크레딧 자동 사용', '만료일이 빠른 추가 크레딧부터'],
    },
    pack: {
      recommended: '추천',
      credits: '{credits} 크레딧',
      bonus: '+{percent}% 보너스',
      validity: '유효 기간 {days}일',
      unavailable: '구매 불가',
      select: '{name} 선택',
      perTenK: '1만 크레딧당 {price}',
      bestValue: '최저 단가',
    },
    purchase: {
      policy: '일회성 구매이며 구매 후 환불되지 않습니다. 유효 기간은 {days}일입니다.',
      agree: '이 일회성 구매는 환불되지 않으며 구매 후 {days}일이 지나면 만료됨을 이해했습니다.',
      buy: '{credits} 크레딧 구매 · {price}',
      choosePack: '크레딧 팩을 선택하세요',
      opening: 'Stripe를 여는 중…',
    },
    summary: { title: '주문 요약', pack: '팩', credits: '크레딧', validity: '유효 기간', validityValue: '{days}일', after: '구매 후 잔액', total: '결제 금액' },
    secure: '결제는 Stripe를 통해 안전하게 처리됩니다',
    upsell: { title: '매달 부족하신가요?', body: '구독 요금제는 월간 크레딧이 더 많고 크레딧당 단가도 더 낮습니다.', action: '구독 요금제 보기 →' },
    errors: {
      failed: 'Stripe Checkout을 열 수 없습니다. 다시 시도해 주세요.',
      rateLimited: '24시간 동안 최대 10건까지 구매할 수 있습니다. 잠시 후 다시 시도해 주세요.',
      reconciliation: '계정의 결제 설정은 고객 지원팀의 확인이 필요합니다. 고객 지원에 문의한 후 다시 시도해 주세요.',
      requestExpired: '이 구매 시도가 만료되었습니다. 새로 구매를 시작해 주세요.',
      billingDisabled: '결제가 일시적으로 중단되었습니다. 나중에 다시 시도해 주세요.',
    },
    canceled: '결제가 취소되어 요금이 청구되지 않았습니다. 선택한 내용은 유지됩니다.',
    result: {
      pendingTitle: '결제를 확인하는 중',
      pendingSummary: 'Stripe에서 결제를 확인하고 있습니다. 완료되는 즉시 크레딧이 추가됩니다.',
      grantedTitle: '크레딧이 추가되었습니다',
      grantedSummary: '{credits} 크레딧이 계정에 추가되었습니다.',
      grantedSummaryUnknown: '추가 크레딧이 계정에 추가되었습니다.',
      failedTitle: '결제가 완료되지 않았습니다',
      failedSummary: '결제에 실패하여 크레딧이 추가되지 않았습니다. 팩을 선택해 다시 시도해 주세요.',
      delayedTitle: '결제를 처리하는 중입니다',
      delayedSummary: '일부 결제 수단은 확인에 시간이 더 걸립니다. 결제가 완료되면 크레딧이 자동으로 추가되니 나중에 구매 내역을 확인해 주세요.',
      unverifiedTitle: '결제가 제출되었습니다',
      unverifiedSummary: '결제 링크가 만료되어 이 페이지에서 주문을 확인할 수 없습니다. Typeflux를 열어 최신 잔액을 확인해 주세요.',
      returnToApp: 'Typeflux로 돌아가기',
      checkAgain: '다시 확인',
    },
    history: {
      title: '구매 내역',
      show: '구매 내역 보기',
      hide: '구매 내역 닫기',
      loading: '구매 내역을 불러오는 중…',
      empty: '아직 크레딧 팩 구매 내역이 없습니다.',
      error: '구매 내역을 불러오지 못했습니다.',
      loadMore: '더 보기',
      date: '구매일',
      pack: '팩',
      credits: '크레딧',
      remaining: '잔여',
      expires: '만료일',
      status: '상태',
      manual: '보상',
      statuses: { active: '사용 가능', frozen: '동결됨', revoked: '회수됨', expired: '만료됨' },
    },
    packs: {
      pack_s: { name: '스몰', description: '가끔 필요한 추가 사용량에 적합' },
      pack_m: { name: '미디엄', description: '기본 요율보다 10% 더 많은 크레딧' },
      pack_l: { name: '라지', description: '기본 요율보다 15% 더 많은 크레딧' },
      pack_xl: { name: '엑스트라 라지', description: '기본 요율보다 25% 더 많은 크레딧' },
    },
  },
}

export function creditPacksCopy(lang) {
  return copy[lang] || copy.en
}

export function formatMessage(template, values) {
  return Object.entries(values).reduce(
    (message, [key, value]) => message.replaceAll(`{${key}}`, String(value)),
    template,
  )
}
